version: '3.4'

services:
  app: &app_base
    container_name: 'rtcdemo_app'
    build:
      context: .
    volumes:
      - ./log:/app/log
      - ./docker/web/uploads:/app/public/uploads
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      REDIS_URL: redis://redis:6379/0
    command: /app/bin/app_start
    depends_on:
      - postgres
      - redis
  worker:
    container_name: 'rtcdemo_worker'
    <<: *app_base
    command: bundle exec sidekiq
  web:
    container_name: 'rtcdemo_web'
    <<: *app_base
    depends_on:
      - app
      - worker
    ports:
      - 80:80
    command: nginx -g 'pid /tmp/nginx.pid; daemon off;'
  postgres:
    container_name: 'rtcdemo_postgres'
    image: postgres:11.1-alpine
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  redis:
    container_name: 'rtcdemo_redis'
    image: redis:4.0-alpine
    volumes:
      - ./docker/redis:/data
