default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>

development:
  <<: *default
  database: rpcdemo_development

test:
  <<: *default
  database: rpcdemo_test

production:
  <<: *default
  database: rpcdemo_production
